import { useState } from "react";
import { Link } from "react-router-dom";
import API from "../api/axios";

const initial = { name: "", email: "", phone: "", company: "", message: "" };

export default function LeadCapture() {
  const [form, setForm] = useState(initial); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { await API.post("/leads", form); setMessage("Thanks — we’ve received your details and will be in touch shortly."); setForm(initial); } catch (err) { setError(err.response?.data?.message || "We couldn't submit your request. Please try again."); } finally { setLoading(false); } };
  return <div className="capture-page"><header className="capture-nav"><Link to="/" className="brand"><span>H</span> HeroCRM</Link><Link to="/login">Team sign in →</Link></header><main className="capture-main"><section className="capture-copy"><p className="eyebrow">LET’S START A CONVERSATION</p><h1>Big ideas deserve a brilliant next step.</h1><p>Tell us a little about what you’re building. Our team will reach out with a thoughtful response, not a generic sales pitch.</p><div className="capture-proof"><span>✓</span><div><strong>Human replies, quickly</strong><small>Usually within one business day</small></div></div></section><section className="capture-card"><p className="eyebrow">GET IN TOUCH</p><h2>How can we help?</h2><p>Share your details and we’ll take it from here.</p>{message && <div className="alert success">{message}</div>}{error && <div className="alert error">{error}</div>}<form className="form-grid" onSubmit={submit}><label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Work email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" /></label><label>Phone number<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value.replace(/\D/g, "").slice(0, 10) })} placeholder="10-digit phone number" /></label><label>Company <em>(optional)</em><input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} placeholder="Your company" /></label><label>What are you looking for? <em>(optional)</em><textarea rows="3" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Tell us a bit about your project" /></label><button className="primary" disabled={loading}>{loading ? "Sending…" : "Send message"} <span>→</span></button></form></section></main></div>;
}
